export const cities = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "New Orleans, LA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "San Francisco, CA",
  "Charlotte, NC",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Washington D.C., DC",
  "Boston, MA",
  "El Paso, TX",
  "Detroit, MI",
  "Nashville, TN",
  "Portland, OR",
  "Memphis, TN",
  "Oklahoma City, OK",
  "Las Vegas, NV",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Mesa, AZ",
  "Sacramento, CA",
  "Atlanta, GA",
  "Kansas City, MO",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Omaha, NE",
  "Miami, FL",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Arlington, TX",
  "Bakersfield, CA",
  "Tampa, FL",
  "Honolulu, HI",
  "Aurora, CO",
  "Anaheim, CA",
  "Santa Ana, CA",
  "St. Louis, MO",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Henderson, NV",
  "Stockton, CA",
  "Saint Paul, MN",
  "Cincinnati, OH",
  "Pittsburgh, PA",
  "Greensboro, NC",
  "Anchorage, AK",
  "Plano, TX",
  "Newark, NJ",
  "Lincoln, NE",
  "Toledo, OH",
  "Orlando, FL",
  "Chula Vista, CA",
  "Irvine, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "Durham, NC",
  "Madison, WI",
  "Laredo, TX",
  "Chandler, AZ",
  "Buffalo, NY",
  "Lubbock, TX",
  "Chesapeake, VA",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Garland, TX",
  "Winston-Salem, NC",
  "Hialeah, FL",
  "Baton Rouge, LA",
  "Richmond, VA",
  "Boise, ID",
  "Spokane, WA",
  "Des Moines, IA",
  "Montgomery, AL",
  "Moreno Valley, CA",
  "Shreveport, LA",
  "Fayetteville, NC",
  "Akron, OH",
  "Mobile, AL",
  "Huntington Beach, CA",
  "Little Rock, AR",
  "Grand Rapids, MI",
  "Salt Lake City, UT",
  "Tallahassee, FL",
  "Tempe, AZ",
  "Harrisburg, PA",
  "Charleston, SC",
  "Overland Park, KS",
  "Knoxville, TN",
  "Cape Coral, FL",
  "Santa Clarita, CA",
  "Vancouver, WA",
  "Peoria, AZ",
  "Sioux Falls, SD",
  "Springfield, MO",
  "Elk Grove, CA",
  "Rockford, IL",
  "West Valley City, UT",
  "Burbank, CA",
  "Carrollton, TX",
  "Murrieta, CA",
  "College Station, TX",
  "Ventura, CA",
  "O'Fallon, MO",
  "Miami Gardens, FL",
  "Newport News, VA",
  "Frisco, TX",
  "Chattanooga, TN",
  "Temecula, CA",
  "Champaign, IL",
  "Macon, GA",
  "Bellevue, NE",
  "Abilene, TX",
  "Pompano Beach, FL",
  "Evansville, IN",
  "Waterbury, CT",
  "Torrance, CA",
  "Columbia, SC",
  "Olympia, WA",
  "Lansing, MI",
  "Round Rock, TX",
  "Tustin, CA",
  "Independence, MO",
  "Killeen, TX",
  "Denton, TX",
  "Arvada, CO",
  "Wilmington, NC",
  "Cedar Rapids, IA",
  "Simi Valley, CA",
  "Carlsbad, CA",
  "Clearwater, FL",
  "Peabody, MA",
  "Green Bay, WI",
  "Fargo, ND",
  "Deltona, FL",
  "Westminster, CO",
  "Inglewood, CA",
  "Richardson, TX",
  "Odessa, TX",
  "Murfreesboro, TN",
  "Lafayette, LA",
  "Greeley, CO",
  "Palm Bay, FL",
  "Pueblo, CO",
  "New Bedford, MA",
  "Clinton, IA",
  "Moorhead, MN",
  "Joliet, IL",
  "Lynchburg, VA",
  "Rock Hill, SC",
  "Sioux City, IA",
  "Kennewick, WA",
  "Gilbert, AZ",
  "Chino, CA",
  "Bossier City, LA",
  "Hattiesburg, MS",
  "Watsonville, CA",
  "Sandy Springs, GA",
  "Coral Springs, FL",
  "Midland, TX",
  "Hickory, NC",
  "Lancaster, CA",
  "Bismarck, ND",
  "Grand Prairie, TX",
  "Eugene, OR",
  "Alameda, CA",
  "North Las Vegas, NV",
  "Gainesville, FL",
  "Bend, OR",
  "Ann Arbor, MI",
  "Grand Junction, CO",
  "Edison, NJ",
  "Burlington, VT",
  "Mansfield, OH",
  "Harrisonburg, VA",
  "Canton, OH",
  "Beaumont, TX",
  "Kingwood, TX",
  "Myrtle Beach, SC",
  "Lima, OH",
  "Norman, OK",
  "Spring Hill, FL",
  "Poughkeepsie, NY",
  "Sherman, TX",
  "Waco, TX",
  "Beavercreek, OH",
  "Boca Raton, FL",
  "Hendersonville, TN",
  "Huntsville, AL",
  "Medford, OR",
  "Kansas City, KS",
  "Jackson, MS",
  "Middletown, OH",
  "San Marcos, TX",
  "Kenosha, WI",
  "Danville, VA",
  "Salem, OR",
  "Vero Beach, FL",
  "Charleston, WV",
  "Springdale, AR",
  "Yuma, AZ",
  "Carmel, IN",
  "Edmond, OK",
  "Fullerton, CA",
  "Missoula, MT",
  "Cedar Park, TX",
  "Mission Viejo, CA",
  "High Point, NC",
  "McKinney, TX",
  "Fredericksburg, VA",
  "Roseville, CA",
  "Bellingham, WA",
  "Carson, CA",
  "Worcester, MA",
  "Redwood City, CA",
  "Rockwall, TX",
  "Fort Collins, CO",
  "Auburn, AL",
  "Kirkland, WA",
  "South Bend, IN",
  "Murray, UT",
  "Northfield, MN"
];